# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    easyroom.form.registration:
        class: EasyRoom\UserBundle\Form\RegistrationType
        tags: 
            - { name: form.type, alias: easyroom_user_registration}
            
    easyroom.form.profile:
        class: EasyRoom\UserBundle\Form\RegistrationType
        tags: 
            - { name: form.type, alias: easyroom_user_profile}
