# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    easyroom.form.registration:
        class: EasyRoom\AppBundle\Form\RegistrationType
        tags: 
            - { name: form.type, alias: easyroom_user_registration}
            
    easyroom.form.profile:
        class: EasyRoom\AppBundle\Form\RegistrationType
        tags: 
            - { name: form.type, alias: easyroom_user_profile}
