index:
    path:     /
    defaults: { _controller: EasyRoomAppBundle:Accueil:index }

easy_room_app_test_index:
    path:     /test
    defaults: { _controller: EasyRoomAppBundle:Test:index }

easy_room_app_salle_creation:
    path:     /salle/creation
    defaults: { _controller: EasyRoomAppBundle:Salle:creation }

easy_room_app_salle_fiche:
    path:     /salle/{idSalle}
    defaults: { _controller: EasyRoomAppBundle:Salle:affichage }

easy_room_app_salle_search:
    path:     /salle
    defaults: { _controller: EasyRoomAppBundle:Salle:search }

easy_room_app_equipement:
    path:     /equipement
    defaults: { _controller: EasyRoomAppBundle:Equipement:index }

easy_room_app_equipement_add:
    path:     /equipement/add
    defaults: { _controller: EasyRoomAppBundle:Equipement:add }

easy_room_app_reservation_index:
    path:     /reservation
    defaults: { _controller: EasyRoomAppBundle:Reservation:index }

easy_room_app_utilisateur_index:
    path:     /utilisateur
    defaults: { _controller: EasyRoomAppBundle:Utilisateur:index }
