services:
    disposition.service:
        class: EasyRoom\AppBundle\Service\DispositionService
        arguments: ["@doctrine.orm.default_entity_manager", %disposition.id.rectangle%, %disposition.id.conference%, %disposition.id.classe%, %disposition.id.vide%]

    salle.service:
        class: EasyRoom\AppBundle\Service\SalleService
        arguments: ["@doctrine.orm.default_entity_manager", "@disposition.service", "@equipement.service", %disposition.id.rectangle%, %disposition.id.conference%, %disposition.id.classe%, %disposition.id.vide%]

    utilisateur.service:
        class: EasyRoom\AppBundle\Service\UtilisateurService
        arguments: ["@doctrine.orm.default_entity_manager", "@role.service"]

    role.service:
        class: EasyRoom\AppBundle\Service\RoleService
        arguments: ["@doctrine.orm.default_entity_manager"]

    equipement.service:
        class: EasyRoom\AppBundle\Service\EquipementService
        arguments: ["@doctrine.orm.default_entity_manager"]

    typeequipement.service:
        class: EasyRoom\AppBundle\Service\TypeEquipementService
        arguments: ["@doctrine.orm.default_entity_manager"]

    reservation.service:
        class: EasyRoom\AppBundle\Service\ReservationService
        arguments: ["@doctrine.orm.default_entity_manager", "@salle.service", "@utilisateur.service", "@equipement.service", "@inviteexterne.service"]

    inviteexterne.service:
        class: EasyRoom\AppBundle\Service\InviteExterneService
        arguments: ["@doctrine.orm.default_entity_manager"]